version: "1.1"

services: 
  node: 
    container_name: reja
    restart: always
    image: hurayrahsam/reja-image
    ports: 
      - 3005:3073
    volumes: 
      - ./:/user/src/app
    working_dir: /user/src/app

    networks: 
      - reja_network
    
    command: bash -c "npm install && npm run dev"


networks: 
  reja_network:
    driver: bridge
